name: Drift Detection

on:
  # Manual trigger
  workflow_dispatch:

  # Scheduled run every day at 6 AM UTC
  schedule:
    - cron: '0 6 * * *'

jobs:
  drift:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
        uses: actions/checkout@v3

    - name: Create temporary directory
        run: mkdir -p tmp
jobs:
  drift:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Create temporary directory
      run: mkdir -p tmp

    - name: Trigger StackGen Drift Detection
      uses: AaravAggarwal/stackgen-drift-detection-action@main
      env:
        STACKGEN_TOKEN: ${{ secrets.STACKGEN_TOKEN }}
        TMPDIR: ${{ github.workspace }}/tmp
        # add any cloud provider creds your appStack needs (ex:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY_ID: ${{ secrets.AWS_SECRETS_ACCESS_KEY_ID}}
      with:
        appstack_id: 'b454489b-9eb9-4f4c-816d-16c73d18b3ce' # this is found in the URL of your appStack after /appstacks/
        region: 'us-east-1'  # e.g. us-east-1