name: Drift Detection

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  drift:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create temporary directory
        run: mkdir -p tmp

      - name: Trigger StackGen Drift Detection
        uses: AaravAggarwal/stackgen-drift-detection-action@main
        env:
          STACKGEN_TOKEN: ${{ secrets.STACKGEN_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TMPDIR: ${{ github.workspace }}/tmp
        with:
          appstack_id: 'b454489b-9eb9-4f4c-816d-16c73d18b3ce'
          region: 'us-east-1'